meson: Remove build type switch
This needs to be set in the package.

Currently, there is no way to override it.

    [BEE] meson --prefix /usr --sysconfdir=/etc --localstatedir=/var --buildtype=plain -Dblkid=true -Dbuildtype=release -Ddefault-dnssec=yes -Ddns-servers=141.14.16.1 -Dntp-servers=zeit.fu-berlin.de ntps1-0.cs.tu-berlin.de time.fu-berlin.de -Dfirstboot=false -Dinstall-tests=false -Dldconfig=false -Drootprefix= -Drootlibdir=/lib -Dsplit-usr=true -Dsysusers=false -Ddefault-kill-user-processes=false -Db_lto=false /dev/shm/bee-root/systemd/systemd-239-0/source
    Traceback (most recent call last):
      File "/pkg/python-3.6.6-1/bin/meson", line 29, in <module>
        sys.exit(mesonmain.main())
      File "/pkg/python-3.6.6-1/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 379, in main
        return run(sys.argv[1:], launcher)
      File "/pkg/python-3.6.6-1/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 330, in run
        coredata.parse_cmd_line_options(options)
      File "/pkg/python-3.6.6-1/lib/python3.6/site-packages/mesonbuild/coredata.py", line 543, in parse_cmd_line_options
        'Got argument {0} as both -D{0} and {1}. Pick one.'.format(name, cmdline_name))
    mesonbuild.mesonlib.MesonException: Got argument buildtype as both -Dbuildtype and --buildtype. Pick one.
    Command exited with non-zero status 1